version: '3.8'
services:    
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: server
    env_file:
      - .env
    ports:
      - "8000:8000"